export const db = [
  {
    id: 1,
    status: 'inactive',
    identifiant: 'gslixby0',
    fullName: 'Galen Slixby',
    nom: 'Slixby',
    prenom: 'Galen',
    tel: '(479) 232-9151',
    email: 'gslixby0@abc.net.au',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 2,
    status: 'pending',
    identifiant: 'hredmore1',
    fullName: 'Halsey Redmore',
    nom: 'Redmore',
    prenom: 'Halsey',
    tel: '(472) 607-9137',
    email: 'hredmore1@imgur.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 3,
    status: 'active',
    identifiant: 'msicely2',
    fullName: 'Marjory Sicely',
    nom: 'Sicely',
    prenom: 'Marjory',
    tel: '(321) 264-4599',
    email: 'msicely2@who.int',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 4,
    status: 'inactive',
    identifiant: 'crisby3',
    fullName: 'Cyrill Risby',
    nom: 'Risby',
    prenom: 'Cyrill',
    tel: '(923) 690-6806',
    email: 'crisby3@wordpress.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 5,
    status: 'pending',
    identifiant: 'mhurran4',
    fullName: 'Maggy Hurran',
    nom: 'Hurran',
    prenom: 'Maggy',
    tel: '(669) 914-1078',
    email: 'mhurran4@yahoo.co.jp',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 6,
    status: 'active',
    identifiant: 'shalstead5',
    fullName: 'Silvain Halstead',
    nom: 'Halstead',
    prenom: 'Silvain',
    tel: '(958) 973-3093',
    email: 'shalstead5@shinystat.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 7,
    status: 'pending',
    identifiant: 'bgallemore6',
    fullName: 'Breena Gallemore',
    nom: 'Gallemore',
    prenom: 'Breena',
    tel: '(825) 977-8152',
    email: 'bgallemore6@boston.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 8,
    status: 'pending',
    identifiant: 'kliger7',
    fullName: 'Kathryne Liger',
    nom: 'Liger',
    prenom: 'Kathryne',
    tel: '(187) 440-0934',
    email: 'kliger7@vinaora.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 9,
    status: 'pending',
    identifiant: 'fscotfurth8',
    fullName: 'Franz Scotfurth',
    nom: 'Scotfurth',
    prenom: 'Franz',
    tel: '(978) 146-5443',
    email: 'fscotfurth8@dailymotion.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 10,
    status: 'inactive',
    identifiant: 'jbellany9',
    fullName: 'Jillene Bellany',
    nom: 'Bellany',
    prenom: 'Jillene',
    tel: '(589) 284-6732',
    email: 'jbellany9@kickstarter.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 11,
    status: 'inactive',
    identifiant: 'jwharltona',
    fullName: 'Jonah Wharlton',
    nom: 'Wharlton',
    prenom: 'Jonah',
    tel: '(176) 532-6824',
    email: 'jwharltona@oakley.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 12,
    status: 'pending',
    identifiant: 'shallamb',
    fullName: 'Seth Hallam',
    nom: 'Hallam',
    prenom: 'Seth',
    tel: '(234) 464-0600',
    email: 'shallamb@hugedomains.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 13,
    status: 'inactive',
    identifiant: 'ypottiec',
    fullName: 'Yoko Pottie',
    nom: 'Pottie',
    prenom: 'Yoko',
    tel: '(907) 284-5083',
    email: 'ypottiec@privacy.gov.au',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 14,
    status: 'active',
    identifiant: 'mkraused',
    fullName: 'Maximilianus Krause',
    nom: 'Krause',
    prenom: 'Maximilianus',
    tel: '(167) 135-7392',
    email: 'mkraused@stanford.edu',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  },
  {
    id: 15,
    status: 'active',
    identifiant: 'zmcclevertye',
    fullName: 'Zsazsa McCleverty',
    nom: 'McCleverty',
    prenom: 'Zsazsa',
    tel: '(317) 409-6565',
    email: 'zmcclevertye@soundcloud.com',
    password: 'azerty',
    avatar: '',
    role: 'agent'
  }
]
